site_name: TRAKI
repo_url: https://github.com/norygami/traki/
repo_name: traki
edit_uri: edit/main/docs/

theme:
  logo: assets/organizations/ARedC.png
  favicon: assets/organizations/ARedC.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - content.tooltips
    - navigation.tabs
    - content.action.edit
  site_url: https://github.com/norygami/traki/
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      construction: material/hammer-wrench
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      secondary: custom
  font:
    text: "Jost"
    code: "Roboto Mono"
plugins:
   - meta
   - blog
   - search
   - awesome-nav
   - glightbox
   - tags
   - git-revision-date-localized:
      enable_creation_date: false
   - social:
      cards_layout_options:
        font_family: Jost
        background_color: black
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/links.md
  - pymdownx.blocks.caption
  - md_in_html
  - footnotes

validation:
  links:
    absolute_links: ignore
    anchors: warn
    unrecognized_links: warn
watch:
- includes
extra_css:
  - stylesheets/extra.css