site_name: TRAKI
repo_url: https://github.com/norygami/traki/
repo_name: traki
edit_uri: edit/main/docs/

theme:
  logo: assets/organizations/ARedC.png
  favicon: assets/organizations/ARedC.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - content.tooltips
    - navigation.tabs
    - content.action.edit
  site_url: https://github.com/norygami/traki/
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      construction: material/hammer-wrench
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      secondary: custom
  font:
    text: "Jost"
    code: "Roboto Mono"
plugins:
   - meta
   - blog:
      pagination_per_page: 3
      blog_toc: true
   - search
   #- panzoom
   - awesome-nav
   - glightbox
   - tags
   - macros
   - table-reader
   - git-revision-date-localized:
      enable_creation_date: false
   - social:
      cards_layout_options:
        font_family: Jost
        background_color: black
   - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
        custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/links.md
  - pymdownx.blocks.caption
  - md_in_html
  - footnotes

validation:
  links:
    absolute_links: ignore
    anchors: warn
    unrecognized_links: warn
watch:
- includes
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - https://unpkg.com/cytoscape@3.26.0/dist/cytoscape.min.js
  - https://unpkg.com/dagre@0.8.5/dist/dagre.min.js
  - https://unpkg.com/cytoscape-dagre@2.5.0/cytoscape-dagre.js