preserve_directory_names: true 
ignore: "*.hidden.md" 

sort:
  direction: asc 
  type: natural 
  by: filename 
  sections: last 
  ignore_case: true 
nav: 
  - News:
      - blog/index.md
  - People
  - Organizations
  - Events
  - Dialogue
ignore: "*_d.md"